#!/usr/bin/env node
/**
 * Regenerate every machine-derived page from the LIVE contract.
 *
 * The rule this repo lives by: nothing that can drift is written by hand. The Loore API publishes one
 * OpenAPI document, and that document is generated on the server from the SAME registry that defines
 * the MCP tools — one `operationId` is both the REST operation and the MCP tool name. So the whole
 * reference (`openapi.json`, the MCP tool table, the counts quoted in prose) is derived from it here,
 * and CI fails when the checked-in output differs from a fresh run (`--check`).
 *
 * Usage:
 *   node scripts/generate.mjs            # rewrite generated files
 *   node scripts/generate.mjs --check    # exit 1 if anything would change (CI gate)
 *   LOORE_OPENAPI_URL=… node scripts/…   # point at another environment
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_URL = process.env.LOORE_OPENAPI_URL ?? "https://app.loore.ai/api/openapi.json";
const CHECK = process.argv.includes("--check");

/** Files this script owns. Anything else in the repo is hand-written and never touched here. */
const GENERATED = ["openapi.json", "mcp/tools.mdx"];

const HEADER =
  "{/* GENERATED by scripts/generate.mjs from the live OpenAPI — do not edit by hand. */}";

async function fetchSpec() {
  const res = await fetch(SPEC_URL, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`${SPEC_URL} → HTTP ${res.status}`);
  const spec = await res.json();
  if (!spec?.paths || typeof spec.paths !== "object") throw new Error("spec has no paths");
  return spec;
}

/** One row per published operation: MCP tool name, REST path, what it does. */
function operations(spec) {
  const rows = [];
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) {
      if (!["get", "post", "put", "patch", "delete"].includes(method)) continue;
      rows.push({
        tool: op.operationId ?? "—",
        method: method.toUpperCase(),
        path,
        summary: (op.summary ?? "").trim(),
        description: (op.description ?? "").trim(),
      });
    }
  }
  rows.sort((a, b) => a.tool.localeCompare(b.tool));
  return rows;
}

/**
 * A cell rendered INSIDE a code span. Braces and angle brackets are literal there, so escaping them
 * would print the backslashes; only the pipe (which ends the cell) and stray backticks matter.
 */
function codeCell(text) {
  return text.replace(/`/g, "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
}

/**
 * A cell rendered as PROSE. Here MDX is live: `{` starts a JS expression and `<` starts a JSX tag,
 * so one description carrying either would break the whole page build. Plus the pipe/newline rules
 * every table cell has.
 */
function proseCell(text) {
  return text
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .replace(/[{}]/g, (brace) => `\\${brace}`)
    .replace(/</g, "&lt;")
    .trim();
}

/** First sentence of a description — the table stays scannable, the API reference has the rest. */
function firstSentence(text) {
  const trimmed = text.replace(/\s+/g, " ").trim();
  const stop = trimmed.search(/\.\s/);
  return stop === -1 ? trimmed : trimmed.slice(0, stop + 1);
}

function toolsPage(spec, rows) {
  const lines = [
    "---",
    'title: "Инструменты MCP"',
    'description: "Полный список инструментов, которые агент получает после подключения Loore MCP."',
    "---",
    "",
    HEADER,
    "",
    `Сервер публикует **${rows.length}** инструментов. Имя инструмента в MCP и \`operationId\` в REST — это одно и то же: подключился по MCP — зовёшь \`ig_analytics\`; пошёл через REST — делаешь \`POST /v1/ig-analytics\`. Одна и та же операция, один и тот же ключ.`,
    "",
    "<Info>",
    "  Список обновляется автоматически из живого контракта API. Если инструмента здесь нет — его нет и на сервере.",
    "</Info>",
    "",
    "| Инструмент (MCP) | REST | Что делает |",
    "| --- | --- | --- |",
  ];
  for (const row of rows) {
    lines.push(
      `| \`${codeCell(row.tool)}\` | \`${codeCell(`${row.method} ${row.path}`)}\` | ${proseCell(firstSentence(row.description || row.summary))} |`,
    );
  }
  lines.push(
    "",
    "## Как вызвать",
    "",
    "<CodeGroup>",
    "",
    "```bash REST",
    "curl -X POST https://mcp.loore.ai/v1/ig-analytics \\",
    '  -H "Authorization: Bearer $LOORE_API_KEY" \\',
    '  -H "Content-Type: application/json" \\',
    `  -d '{"handle":"@brand"}'`,
    "```",
    "",
    "```text MCP",
    "Подключи https://mcp.loore.ai/mcp с заголовком Authorization: Bearer <ключ>",
    "и вызови инструмент ig_analytics с аргументом handle.",
    "```",
    "",
    "</CodeGroup>",
    "",
    "Ответ всегда приходит в одном конверте: `{ status, error?, details?, result? }`.",
    "",
  );
  return `${lines.join("\n")}`;
}

async function readIfExists(path) {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

async function emit(relative, content) {
  const target = join(ROOT, relative);
  const current = await readIfExists(target);
  if (current === content) return { relative, changed: false };
  if (!CHECK) {
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
  }
  return { relative, changed: true };
}

const spec = await fetchSpec();
const rows = operations(spec);
const results = await Promise.all([
  emit("openapi.json", `${JSON.stringify(spec, null, 2)}\n`),
  emit("mcp/tools.mdx", toolsPage(spec, rows)),
]);

const changed = results.filter((r) => r.changed).map((r) => r.relative);
console.log(`spec: ${SPEC_URL}`);
console.log(`operations: ${rows.length}`);
console.log(`generated files: ${GENERATED.join(", ")}`);

if (CHECK && changed.length > 0) {
  console.error(`\nOUT OF SYNC — regenerate with \`node scripts/generate.mjs\`:\n${changed.join("\n")}`);
  process.exit(1);
}
console.log(changed.length > 0 ? `updated: ${changed.join(", ")}` : "already up to date");
